# -*- coding: utf-8 -*-
"""bigBang-NoorsyahirahAlya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBHvVJKSFMhQFpPf0A32TdovNeyUshPJ
"""

import json

result = []
for num in range(1, 101):
    if num % 3 == 0 and num % 5 == 0:
        result.append("BIG BANG")
    elif num % 3 == 0:
        result.append("BIG")
    elif num % 5 == 0:
        result.append("BANG")
    else:
        result.append(num)

output_file = "output.json"
with open(output_file, "w") as f:
    json.dump(result, f)

print(f"Output has been saved to {output_file}.")
